### ISSUE TITLE
Additional email address : 这个email address 会收到所有发比这个attendee 的email **  随了create account 的username password email 

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#129]
![snip20160130_8](https://cloud.githubusercontent.com/assets/16773800/12695898/babc6b0a-c796-11e5-9568-427d89f9faf5.png)

**Comment by riseno** [comment]
@herberttse 

how about tell a friend?

**Comment by herberttse** [comment]
@riseno 

tell a friend 的email 只是发给 在success page 上填的那那个email . 不用去additional email additional email

**Comment by riseno** [comment]
then its fixed by above commit.
