### ISSUE TITLE
Create account email - program

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#130]
1/ 无subject
2/ send by 不用出email 
3/ 英文的多了一组password
![snip20160130_9](https://cloud.githubusercontent.com/assets/16773800/12695928/ae7d5830-c797-11e5-9032-c9e49defe052.png)

**Comment by riseno** [comment]
fixed @aa9d17956b00f50181d2dcd5643a30ebc9e3501b
