### ISSUE TITLE
create account email - email layout

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#131]
1/ 字体不一样
2/ 每一点分开上下分开D
3/ 每个email 的这一行Admission to ....，都是最下的一行，字体要小一至二个size, 中英文也一样

![snip20160130_10](https://cloud.githubusercontent.com/assets/16773800/12695963/433f960e-c798-11e5-868f-a8b459b084c7.png)

**Comment by riseno** [comment]
@herberttse 

should have fixed. so i close this issue first. if any issue occurred, reopen it.

**Comment by herberttse** [comment]
OK noted
