### ISSUE TITLE
Submit payment page - layout and cap 错info

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#137]
1/ personal info , 的外框不要
2/ 中文公司名出了 primary email
3/ additional email, 我没有填，但是也自动fill 了primary email , 如没有填，空白了他
![snip20160130_18](https://cloud.githubusercontent.com/assets/16773800/12696352/bef4c930-c7a3-11e5-9616-68250408e790.png)

**Comment by riseno** [comment]
00e461da631ca634eea1feb9af6a0472315829ef
