### ISSUE TITLE
submit payment page - Apply code / change code , drop down change pass

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#140]
1/ need to check if he need to go back to personal detail form to refill the form

刚 选了IEP 然后在这里apply Gold discount code, 价钱对，但是没有回去personal detail 重新填资料

**Comment by riseno** [comment]
@herberttse 

This issue have been resolved right?

**Comment by herberttse** [comment]
@ riseno fixed the apply code function but we still need a drop down to Change pass only , without applying a code

**Comment by riseno** [comment]
duplicated #139  on dropdown list for changing pass
