### ISSUE TITLE
Reg Home - Active Pending - Complete your registration 要去submit payment page, 

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#147]
因为他已经是 有pass type 的 active pending 应该是去submit payment
现在是去了select pass 的4块胶布

![snip20160130_38](https://cloud.githubusercontent.com/assets/16773800/12696700/25668516-c7ac-11e5-82d8-459f0379a7ae.png)

**Comment by riseno** [comment]
@herberttse 

is this issue resolved?

**Comment by herberttse** [comment]
@ riseno yes , works fine now
