### ISSUE TITLE
Reg Home - resend latest reg email - No function , Resend to Primary and additional email if any , 加这里可以多打一个其他的email 

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#149]
Message:

> Your latest registration email will send to your primary and additional (if applicable) email addresses.
> Would you also like to send it to another email address?

--Send
--Cancel

![snip20160131_43](https://cloud.githubusercontent.com/assets/16773800/12696878/17b65e60-c7b0-11e5-995e-f7f3540a915b.png)

**Comment by riseno** [comment]
@herberttse 

will also CC to additional email right?

**Comment by riseno** [comment]
@herberttse 

send out registration email or final confirmation?
