### ISSUE TITLE
Reg Home - Reg Flow issue - Wrong Pass and Flow

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#159]
1/ 我在welcome page select 了sliver, 个过不到有 error, 那我就back , 回去
2/ 我按 apply sessions 
3/ 在apply sessions 按reg home 
4/ 就是出错像下面，选了 Silver pass , 而且 paid complete 

应该是active pending , 

![snip20160131_61](https://cloud.githubusercontent.com/assets/16773800/12697281/94f68b5c-c7ba-11e5-93c2-c9fe18870a14.png)

**Comment by riseno** [comment]
@herberttse 

should have resolved. please check.

**Comment by herberttse** [comment]
Yes this one is complete

Ryan Chan <notifications@github.com<mailto:notifications@github.com>> ? 2016?2?2? ??6:22 ???


@herberttse<https://github.com/herberttse>

should have resolved. please check.

-
