### ISSUE TITLE
Login to my account

### ISSUE THREAD

**Issue by roylui** [JemexIdeas/JemexEvent#171]
Login back to account > Update your personal information / contact preferences > payment page submit button disappear
![image](https://cloud.githubusercontent.com/assets/16040819/12703758/dcd39cf0-c885-11e5-8325-04dcd8fcdf9b.png)

**Comment by riseno** [comment]
@roylui 

what have you done before logout?

**Comment by herberttse** [comment]
@riseno @Crystaltsn @roylui 
retest today: 0204n@mail.com
payment pending first and then logout and log back in, complete reg in reg home to redirect to payment page, 
both payment method have confirm button
Close it for now
