### ISSUE TITLE
Create account - LinkedIn Function, 入完username and password 后，return 不到system，出只了下面页面

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#172]
![snip20160201_69](https://cloud.githubusercontent.com/assets/16773800/12703773/2c2a19fa-c886-11e5-862f-75d926c7f795.png)

**Comment by riseno** [comment]
@herberttse 

Please check that the linkedIn connect should have resolved.

**Comment by herberttse** [comment]
Still error message
InvalidStateException in AbstractProvider.php line 191:

Ryan Chan <notifications@github.com<mailto:notifications@github.com>> 於 2016年2月2日 下午6:53 寫道：


@herberttse<https://github.com/herberttse>

Please check that the linkedIn connect should have resolved.

**Comment by riseno** [comment]
@herberttse which domain?

**Comment by herberttse** [comment]
I am testing at JUAT but the error message is in dev.xxxxxx

Ryan Chan <notifications@github.com<mailto:notifications@github.com>> 於 2016年2月2日 下午6:59 寫道：


@herberttse<https://github.com/herberttse> which domain?

**Comment by riseno** [comment]
@herberttse 

ok, so i will switch linkedin redirect url to juat domain for testing only. 

And please don't complain that the dev.exhibitorservicemanual.com linkedin is broken.

Coz the application is located at same server.

@roylui @Crystaltsn

**Comment by herberttse** [comment]
Ok , please change to JUAT link

Ryan Chan <notifications@github.com<mailto:notifications@github.com>> 於 2016年2月2日 下午7:12 寫道：


@herberttse<https://github.com/herberttse>

ok, so i will switch linkedin redirect url to juat domain for testing only.

And please don't complain that the dev.exhibitorservicemanual.com<http://dev.exhibitorservicemanual.com> linkedin is broken.

Coz the application is located at same server.

@roylui<https://github.com/roylui> @Crystaltsn<https://github.com/Crystaltsn>
