### ISSUE TITLE
Registration Home > your -- 串錯字

### ISSUE THREAD

**Issue by roylui** [JemexIdeas/JemexEvent#173]
![image](https://cloud.githubusercontent.com/assets/16040819/12703793/7e160a6c-c886-11e5-9189-b870b8f4dec0.png)

**Comment by herberttse** [comment]
Just update the language file at en/reghome , Ryan please help upload...

**Comment by riseno** [comment]
The text should have resolved by @herberttse  on 8f1abebe6538e40a4477aa6ebb040d2eb1c1b663
