### ISSUE TITLE
Reg Home - Upgrade logic - 所有Free 的 其他Pass 类，没有Upgrade pass and Upgrade with code button 

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#175]
#174 
![snip20160201_72](https://cloud.githubusercontent.com/assets/16773800/12703872/b17eb780-c888-11e5-9dd1-f4560ac682bb.png)

**Comment by riseno** [comment]
@herberttse 

is this issue resolved?

**Comment by herberttse** [comment]
I need to check when u done the apply code function at welcome page

Is this fix ? I believe I saw it some moment ago

Ryan Chan <notifications@github.com<mailto:notifications@github.com>> 於 2016年2月2日 下午7:00 道：


@herberttse<https://github.com/herberttse>

is this issue resolved?

―

**Comment by riseno** [comment]
@herberttse 

Ok, this issue is related to the buttons that won't be shown to user when the user is on specific type.

**Comment by herberttse** [comment]
Yes also make sure below will not have also
1 reg status : active pending
2 Gold pass


Ryan Chan <notifications@github.com<mailto:notifications@github.com>> 於 2016年2月2日 下午7:14 道：


@herberttse<https://github.com/herberttse>

Ok, this issue is related to the buttons that won't be shown to user when the user is on specific type.

―
