### ISSUE TITLE
Final Confirmation - 本来选了IEP , 在Submit payment 换了speaker , 收不到QR code 的 Final confirmation, InBOX 里也没有

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#177]
![snip20160201_79](https://cloud.githubusercontent.com/assets/16773800/12704450/5b8324ca-c896-11e5-81df-ae3196adf6eb.png)

**Comment by herberttse** [comment]
刚做过testing , 如没有change pass type 是会收到 Final Confirmation
![snip20160201_80](https://cloud.githubusercontent.com/assets/16773800/12704498/571b8fa2-c897-11e5-9658-613e0ad4ab69.png)

**Comment by herberttse** [comment]
刚又试了，有change pass type 个是是 change to Paid pass 就有收到FC 

我估，应该是 Free Pass 没有收到FC

**Comment by riseno** [comment]
@herberttse 

please try this again. should have resolved by previous commit.

**Comment by herberttse** [comment]
主要是free pass 收不到email , 跟change pass ]PS

Ryan Chan <notifications@github.com<mailto:notifications@github.com>> 於 2016年2月2日 下午7:02 道：


@herberttse<https://github.com/herberttse>

please try this again. should have resolved by previous commit.

―

**Comment by herberttse** [comment]
@riseno @Crystaltsn 
Retest Today: 0204m@mail.com
apply code in submit payment page and change to Free Reg reg, can received email in reg inbox
close case for now
