### ISSUE TITLE
Personal Detail - IEP 和Exhibitor Staff 是没有profile

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#180]
![snip20160201_82](https://cloud.githubusercontent.com/assets/16773800/12704579/4208201a-c899-11e5-9a22-8a793027a2c1.jpg)

**Comment by herberttse** [comment]
@riseno Important!! reg flow please fix

**Comment by riseno** [comment]
@herberttse all IEP types right?

**Comment by herberttse** [comment]
@riseno, Yes all IEP and Exhibitor / Partner Staff Pass, No Profile 6 dropdown question

**Comment by herberttse** [comment]
@riseno 看见没有了profile, 但是按submit 没有反应，过不了…
可能view 是看不到，但是还有checking 在？

**Comment by riseno** [comment]
fixed by [8352d0d]
