### ISSUE TITLE
VISA Request - VISA PDF Email - Paid Complete 后，收不到PDF 的那个信

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#185]
![snip20160201_83](https://cloud.githubusercontent.com/assets/16773800/12704745/5e3d2278-c89c-11e5-894f-daf5f240d913.png)

**Comment by riseno** [comment]
@herberttse 

Please note that the PDF will not be generated by now. Due to chinese font issue have not been fixed

**Comment by herberttse** [comment]
@riseno noted, but can i receive this letter first? without PDF 的email 也先发出去

**Comment by riseno** [comment]
@herberttse Yes, you will receive both letters.
