### ISSUE TITLE
Success Page -Tell a friend Text

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#186]
> Do you have additional contacts/colleagues who you would like GSMA to send information regarding the event?

The email have been sent to your friend.
CHANGE TO: 

> An email has successfully been sent to your friend / colleague.

![snip20160201_85](https://cloud.githubusercontent.com/assets/16773800/12708031/2020ff48-c8d6-11e5-9175-111de5f3032f.png)

**Comment by riseno** [comment]
@herberttse 

Please provide Chinese version as well

@keithwong813 

Do this when you started to working on localization

**Comment by herberttse** [comment]
@riseno 
Chinese text

> 告诉朋友
> 
> 请问您有没有额外的联络人或合作人想收到来自GSMA发出有关展会的信息??
> 
> 名字	
> 姓氏	
> 邮箱

**Comment by riseno** [comment]
@herberttse missing success message in chinese version

**Comment by herberttse** [comment]
You mean the text for whole page ? Or just tell a friend section ?

Ryan Chan <notifications@github.com<mailto:notifications@github.com>> ? 2016?2?2? ??7:22 ???


@herberttse<https://github.com/herberttse> missing success message in chinese version

-

**Comment by riseno** [comment]
@herberttse got the chinese message from @roylui thanks.

**Comment by herberttse** [comment]
Ok

Ryan Chan <notifications@github.com<mailto:notifications@github.com>> ? 2016?2?2? ??7:44 ???


@herberttse<https://github.com/herberttse> got the chinese message from @roylui<https://github.com/roylui> thanks.

-
