### ISSUE TITLE
Success Page -Tell a friend 收不到email. 

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#187]

**Comment by riseno** [comment]
@herberttse 

just tested. it can be received.

**Comment by riseno** [comment]
![screen shot 2016-02-02 at 2 58 20 pm](https://cloud.githubusercontent.com/assets/14790405/12742082/6d228f2c-c9bd-11e5-8713-61edbc954767.png)

**Comment by herberttse** [comment]
@riseno  can receive in Gmail, 但是@jemexideas.com , header footer 未有

**Comment by riseno** [comment]
@herberttse will check it

**Comment by herberttse** [comment]
@riseno @Crystaltsn 
retest today: 0204i@mail.com
gmail can received , with header
not jemex account. please investigate together if it is the domain problem. 
close it for now
same with #243
