### ISSUE TITLE
未完成reg process, 未畀錢就Paid complete??

### ISSUE THREAD

**Issue by Crystaltsn** [JemexIdeas/JemexEvent#197]
![image](https://cloud.githubusercontent.com/assets/16987335/12713531/9289deda-c8cf-11e5-93ed-13d5fccdadf2.png)

Can't continue from #196

**Comment by herberttse** [comment]
@Crystaltsn @riseno 
Retest today : 0204l@mail.com
seems alright now, tested discount code, member code and buy full price.
have go go submit payment page
close it for now
