### ISSUE TITLE
Apply code後error

### ISSUE THREAD

**Issue by Crystaltsn** [JemexIdeas/JemexEvent#198]
Apply 咗個Silver code之後，咩都冇填就直接去咗Reg Home同變咗Paid complete???
之後click update info
![image](https://cloud.githubusercontent.com/assets/16987335/12713632/11ba80b0-c8d0-11e5-9247-d6140c0dc41a.png)

就出咗呢頁
![image](https://cloud.githubusercontent.com/assets/16987335/12713625/0cf27d44-c8d0-11e5-9a24-f8b25a26b139.png)

**Comment by riseno** [comment]
issue have been resolved by implemented modal view for applying code.
