### ISSUE TITLE
Landing page - Forgot Password - 填了email 去reset password, mail box 收到email , 但是 reg home inbox 收不到

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#204]

**Comment by riseno** [comment]
@herberttse 

low priority for this. Using default authentication method. At least its working well by now, will enhance later.

**Comment by herberttse** [comment]
@riseno @Crystaltsn 
retest today: 0204b@mail,com and 0204k@mail.com
works fine on both complete paid and active paid account. 
close it for now
