### ISSUE TITLE
Payment page currency

### ISSUE THREAD

**Issue by Crystaltsn** [JemexIdeas/JemexEvent#207]
要指住先睇到個currency
![image](https://cloud.githubusercontent.com/assets/16987335/12720591/e433ce90-c8fb-11e5-83de-f9cca01e30c7.png)
![image](https://cloud.githubusercontent.com/assets/16987335/12720593/e89f247a-c8fb-11e5-9eae-102c8aa883aa.png)

係price前加返個currency,e.g. USD/RMB
![image](https://cloud.githubusercontent.com/assets/16987335/12720626/07873e22-c8fc-11e5-8cb0-a198f9795394.png)

轉currency時會出現咁，可唔可以avoid?
![image](https://cloud.githubusercontent.com/assets/16987335/12720666/224a8aa2-c8fc-11e5-992a-a37acf41dcc6.png)

**Comment by riseno** [comment]
@Crystaltsn 

Please provide your browser name & version. 

**FYI, IE version equal / below 7 will not be supported.**

**Comment by riseno** [comment]
@Crystaltsn 

For your last question. It can't be avoided. Its HTML Dom placeholder for js framework. if your browser load faster, it won't be shown to users.

**Comment by Crystaltsn** [comment]
Version 48.0.2564.97 m
Google Chrome
