### ISSUE TITLE
Reg page tab title

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#208]
Charge to

> GSMA Mobile World Congress Shanghai 2016

![snip20160202_126](https://cloud.githubusercontent.com/assets/16773800/12739262/e3d11ffa-c9a2-11e5-828b-fc666451e6bc.png)

**Comment by herberttse** [comment]
@riseno 
please help fix this first, i need to send out the testing to client now

**Comment by riseno** [comment]
@herberttse 

give me a name

**Comment by herberttse** [comment]
@riseno GSMA Mobile World Congress Shanghai 2016

**Comment by herberttse** [comment]
@riseno deployed?

**Comment by riseno** [comment]
@herberttse 

deploying

**Comment by riseno** [comment]
@herberttse 
go

**Comment by herberttse** [comment]
@riseno OK, saw it
