### ISSUE TITLE
Upgrade Pass - 已经是Silver Pass  - Drop down 选pass option 应该只有Gold, 和没有will direct 去personal detail 那一段

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#214]
Upgrading your pass will redirect ...... 这句不需要，如果是Silver upgrade 的话

![snip20160202_138](https://cloud.githubusercontent.com/assets/16773800/12740356/62d02fd0-c9ad-11e5-85c7-38438b5955da.png)

**Comment by herberttse** [comment]
#215

**Comment by riseno** [comment]
duplicated with #215

**Comment by herberttse** [comment]
Upgrade with Code 那个button,  还是有这个问题

[cid:4F26E3A0-A0DF-4EC2-AFE5-E9AC12606B54]

**Comment by herberttse** [comment]
@riseno  还有IEP 的，
而且应该不需要redirect page 因为我现在是silver 去Gold , 
***Silver 去Gold 不用redirect 去personal detail 

![snip20160203_178](https://cloud.githubusercontent.com/assets/16773800/12772951/a27b8336-ca71-11e5-8b62-8dc45f3d2612.png)

**Comment by herberttse** [comment]
@riseno @Crystaltsn 
Retest today: 0204i@mail.com
Upgrade Pass button, seems alright now
 - IEP only have Silver and Gold in drop down
 - Silver only have Gold in drop down
