### ISSUE TITLE
Upgrade with code - 已经是Silver pass, 但是他还是可以apply 到另一个Free 的Silver

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#215]
![snip20160202_139](https://cloud.githubusercontent.com/assets/16773800/12740643/ff4923f6-c9af-11e5-9fba-cfe52b25a064.png)

**Comment by riseno** [comment]
@herberttse 

please provide the error message.

**Comment by herberttse** [comment]
@riseno 
per talked, 
if button in "upgrade pass," 在drop down 不给他选自己和比他小的pass
如果是 " Upgrade with code" 如入比他小或跟他一样level 的 free code , (upgrade discount code and men code)    跟上面一样，不给他在dropdown 选

Free Code 的话，出以下的
The code you entered is not valid for your upgrade. Please enter a valid code to continue 

flow 可以？

**Comment by riseno** [comment]
@herberttse please try
