### ISSUE TITLE
Welcome page - Apply discount 后，按Confirm ，价钱没有出新的折后价

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#219]
![snip20160202_142](https://cloud.githubusercontent.com/assets/16773800/12741034/e03f7470-c9b3-11e5-857d-57100a43d9f7.png)

**Comment by Crystaltsn** [comment]
冇show price?
![image](https://cloud.githubusercontent.com/assets/16987335/12752698/04f1d6f4-c9c4-11e5-92c7-f51ecd2042ce.png)

@riseno

**Comment by herberttse** [comment]
只出了IEP , silver and gold 无出到折后价
