### ISSUE TITLE
Upgrade - Upgrade with discount code, 用到，应该是只能用upgrade discount code 

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#223]
![snip20160202_145](https://cloud.githubusercontent.com/assets/16773800/12741846/209e6b82-c9bb-11e5-91e0-3565f1639324.png)

**Comment by riseno** [comment]
@herberttse 

has prefix for that code right?

**Comment by herberttse** [comment]
@riseno yes , UPG (15 30 50) + 5 digit
Can u also create 3 to me ? UPG15/30/50

**Comment by riseno** [comment]
@herberttse 

sure. please wait.
