### ISSUE TITLE
VISA letter invitation attached - Problem

### ISSUE THREAD

**Issue by roylui** [JemexIdeas/JemexEvent#228]
1. registered in Eng page but received Chi vr.
2. Formatting problem, so style and banner, footer

![image](https://cloud.githubusercontent.com/assets/16040819/12743606/d079f766-c9c9-11e5-84c1-9325f587681c.png)

**Comment by riseno** [comment]
@roylui 

wontfix layout issue by now. due to all email templates have overwritten by @keithwong813 new email template updates.

**Comment by roylui** [comment]
How about wrong language letter sending?

**Comment by riseno** [comment]
@roylui 

have been fixed by @7e230cc4f6ff19b498e55a8c65a15f1496ef5f0b this commit
