### ISSUE TITLE
Reg Home - Update personal info - 是free code, 应该是结束很 就回去reg home 现在去了payment page $0

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#245]
![snip20160202_157](https://cloud.githubusercontent.com/assets/16773800/12750017/2a33dc84-c9ef-11e5-8c3c-71a7c1975ccc.png)

**Comment by herberttse** [comment]
@riseno Important!! reg flow please fix

**Comment by riseno** [comment]
@herberttse Please try again. should have resolved. if done, close the issue for me

**Comment by herberttse** [comment]
@riseno , No, the problem still there. you can login my account 0203b@mail.com pw:123456 
- click update info
- update something and click continue 
- then will go the payment page...

**Comment by herberttse** [comment]
@riseno 当了我是upgrade , update 完info 当了我是upgrade 

![snip20160203_175](https://cloud.githubusercontent.com/assets/16773800/12772458/3f013e90-ca6c-11e5-986c-777e80d381c8.png)
