### ISSUE TITLE
pop up message if enter the code is invalid

### ISSUE THREAD

**Issue by roylui** [JemexIdeas/JemexEvent#248]
![image](https://cloud.githubusercontent.com/assets/16040819/12750171/5590dcb4-c9f0-11e5-842d-ba8a25a1e8c8.png)

![image](https://cloud.githubusercontent.com/assets/16040819/12750151/3464a9c6-c9f0-11e5-97e2-8d56143aa867.png)

The code you entered is not valid, please try again.

Refer to "Need help?" section for more information on Discount Codes, Registration Codes and Member Discounts.

**Comment by herberttse** [comment]
@riseno 
现在按confirm 是停了好似死鱼....  严重漏洞

1/ 按confirm , check 到是没有的code .i不用pop up , 在个透明胶布浮D字， 红色，button 转OK. 
2/ 一按OK 下去，自动清code , OK button 转翻做 confirm，比人重新入，

Flow OK??

**Comment by riseno** [comment]
@herberttse please try
