### ISSUE TITLE
Last Name shouldn't be able to edit

### ISSUE THREAD

**Issue by Crystaltsn** [JemexIdeas/JemexEvent#250]
Create 咗account 之後Last Name唔可以改
![image](https://cloud.githubusercontent.com/assets/16987335/12750499/10df4b2e-c9b8-11e5-8447-974b5b0e573e.png)

**Comment by riseno** [comment]
Reason?

**Comment by Crystaltsn** [comment]
It's their business rule
Once account created, email and last name can't be edited. 
But backend user can edit in backend

**Comment by riseno** [comment]
Nice rule from the ass. totally retarded.

Anyway, will update it asap. stay tuned!

**Comment by herberttse** [comment]
@riseno @Crystaltsn 
retest today: 0204e@mail.com
case seems alright, close it for now
