### ISSUE TITLE
Pass Selection Page Apply Code

### ISSUE THREAD

**Issue by Crystaltsn** [JemexIdeas/JemexEvent#254]
有個小4方格係中間？
![image](https://cloud.githubusercontent.com/assets/16987335/12752820/8f6f400a-c9c4-11e5-8168-703dd2001133.png)

**Comment by riseno** [comment]
@Crystaltsn 

Please check, if done, close the issue for me. thx

**Comment by Crystaltsn** [comment]
Now it's ok
