### ISSUE TITLE
Upgrade - Upgrade with discount code, 入member code ，到payment page, 减了currency pass value 后，没有比翻个30% off discount 

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#258]
apply member code in upgrade
(original value pass - old pass ) * 30% off]

![snip20160203_169](https://cloud.githubusercontent.com/assets/16773800/12756188/8b8a0c2e-ca0d-11e5-9d2d-37d6e6c5c32b.png)

**Comment by riseno** [comment]
@herberttse 

negative, can't produce the issue. 

1. purchased IEP 
2. upgrade with code -> enter member code
3. chose silver pass
4. redirected to personal info page
5. submit & redirect to payment page
6. all summary info is correct with discount & current pass value.

Please describe how you produce this issue thx.

**Comment by herberttse** [comment]
@riseno is show the discount and discounted price now , just 2个红框上下对调就OK了，等人知道是减完，才discount

![snip20160203_171](https://cloud.githubusercontent.com/assets/16773800/12772114/696e1868-ca69-11e5-9839-42b583d36afa.png)

**Comment by herberttse** [comment]
再用 UPG30SFJDU upgrade discount code 上gold
只减了价钱，没有apply discount percentage


![snip20160203_172](https://cloud.githubusercontent.com/assets/16773800/12772210/208a5476-ca6a-11e5-9e42-43bfe50dc989.png)

**Comment by riseno** [comment]
@herberttse 

Please try again. missing discount segment in the database, that's why the discount section won't show up

**Comment by herberttse** [comment]
@riseno is alright now, same issue above, 上下调位

![snip20160203_173](https://cloud.githubusercontent.com/assets/16773800/12772359/9c846f48-ca6b-11e5-9b37-005f7136b8ad.png)

**Comment by riseno** [comment]
-
