### ISSUE TITLE
Upgrade - Upgrade with Free Silver and Free good

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#266]
Upgrade with Code
1. IEP to Free Silver 没有redirect to personal detail page , 真直去了successful page
2. IEP to Free gold  正确地没有redirect to personal detail page, 去了successful pass , 然后去home, 但是有upgrade button... Gold pass 应该是没有upgrade button
![snip20160203_184](https://cloud.githubusercontent.com/assets/16773800/12775846/1d60aa9e-ca8c-11e5-988e-24d958954395.png)

**Comment by riseno** [comment]
fixed
